name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t brunosalapic/multi-client ./client
      - run: docker build -t brunosalapic/multi-nginx ./nginx
      - run: docker build -t brunosalapic/multi-server ./server
      - run: docker build -t brunosalapic/multi-worker ./worker
      - run: docker push brunosalapic/multi-client
      - run: docker push brunosalapic/multi-nginx
      - run: docker push brunosalapic/multi-server
      - run: docker push brunosalapic/multi-worker
      
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: brunoEBS
          environment_name: brunoEBS-env
          existing_bucket_name: elasticbeanstalk-us-east-2-477593153981
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip